[files]
extend-exclude = ["warren/embbed_devtool.mbt", "rui/markdown/__fixtures__/ripgrep-README.md",
  "rui/markdown/__fixtures__/async-0.22.2-README.md",
  "rui/markdown/async_readme_test.mbt", "rui/markdown/ripgrep_test.mbt"]

[default.extend-words]
childs = "childs"
seeked = "seeked"
ths = "ths"
