name = "local/__WARREN_PROJECT_NAME__"

version = "0.1.0"

import {
  "moonbit-community/rabbita@__RABBITA_VERSION__",
  "moonbitlang/async@0.21.0",
  "moonbitlang/moonback@0.8.3",
  "moonbitlang/x@0.5.1",
}

readme = "README.md"

repository = ""

license = "Apache-2.0"

keywords = [ ]

description = "A Rabbita app with a Moonback server generated by Warren."

preferred_target = "js"
